DATA_REGISTER_1 = ''
DATA_REGISTER_2 = ''
DATA_REGISTER_3 = ''
DATA_REGISTER_4 = ''
DATA_REGISTER_5 = ''
DATA_REGISTER_6 = ''
DATA_REGISTER_7 = ''
DATA_REGISTER_8 = ''
DATA_REGISTER_9 = ''
DATA_REGISTER_10 = ''
DATA_REGISTER_11 = ''
DATA_REGISTER_12 = ''
DATA_REGISTER_13 = ''
DATA_REGISTER_14 = ''
DATA_REGISTER_15 = ''
DATA_REGISTER_16 = ''

DATA_REGISTERS = [
    DATA_REGISTER_1,
    DATA_REGISTER_2,
    DATA_REGISTER_3,
    DATA_REGISTER_4,
    DATA_REGISTER_5,
    DATA_REGISTER_6,
    DATA_REGISTER_7,
    DATA_REGISTER_8,
    DATA_REGISTER_9,
    DATA_REGISTER_10,
    DATA_REGISTER_11,
    DATA_REGISTER_12,
    DATA_REGISTER_13,
    DATA_REGISTER_14,
    DATA_REGISTER_15,
    DATA_REGISTER_16
]

VAR_REGISTER_1 = []
VAR_REGISTER_2 = []
VAR_REGISTER_3 = []
VAR_REGISTER_4 = []
VAR_REGISTER_5 = []
VAR_REGISTER_6 = []
VAR_REGISTER_7 = []
VAR_REGISTER_8 = []
VAR_REGISTER_9 = []
VAR_REGISTER_10 = []
VAR_REGISTER_11 = []
VAR_REGISTER_12 = []
VAR_REGISTER_13 = []
VAR_REGISTER_14 = []
VAR_REGISTER_15 = []
VAR_REGISTER_16 = []

VAR_REGISTERS = [
    VAR_REGISTER_1,
    VAR_REGISTER_2,
    VAR_REGISTER_3,
    VAR_REGISTER_4,
    VAR_REGISTER_5,
    VAR_REGISTER_6,
    VAR_REGISTER_7,
    VAR_REGISTER_8,
    VAR_REGISTER_9,
    VAR_REGISTER_10,
    VAR_REGISTER_11,
    VAR_REGISTER_12,
    VAR_REGISTER_13,
    VAR_REGISTER_14,
    VAR_REGISTER_15,
    VAR_REGISTER_16
]

TEMP_REGISTER1 = ''
TEMP_REGISTER2 = ''
TEMP_REGISTER3 = ''

TEMP_REGISTERS = [
    TEMP_REGISTER1,
    TEMP_REGISTER2,
    TEMP_REGISTER3
]